### ISSUE TITLE
Contributors Menu Visibility Issue

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#100]
The "Contributors" menu should be accessible and visible to all users, regardless of whether they are logged in or not.

**Steps to Reproduce:**

1. Visit the SnapURL web application: https://app.dturl.live
2. Observe that the "Contributors" menu is not visible in the navbar when not logged in.
3. Log in to the application, and note that the "Contributors" menu becomes visible.

**Comment by mjubair** [comment]
@DhananjayThomble I have added a PR for this issue, please review. hope this meets your requirements.
