### ISSUE TITLE
URL Categories Feature Implementation

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#101]
**Expected Behavior:**
Users should be able to create and assign categories to their shortened URLs. The categories should be displayed in the user's profile, and URLs can be filtered based on these categories.

**Tasks:**

- Design the user interface for creating and managing URL categories.
- Implement the backend logic to associate URLs with categories.
- Add filtering options to view URLs by category.

**Comment by Vidit-Kushwaha** [comment]
Hey! @DhananjayThomble can you assign to me
