### ISSUE TITLE
Application breaks when an unathenticated user tries to shorten link

### ISSUE THREAD

**Issue by ddddami** [DhananjayThomble/URL-Shortener-App#107]
![Screenshot (27)](https://github.com/DhananjayThomble/URL-Shortener-App/assets/82976159/548bd84c-d31f-4b78-afe2-c92a1efb296a)

There should be like an alert sayiing you have to be logged in first (if you want users to logged in before using the app). I feel this should be a quick tool to use, no need for logging in, just paste your link and grab.. but anyways, i also don't know how stuffs are on the backend
#110

**Comment by DhananjayThomble** [comment]
> ![Screenshot (27)](https://user-images.githubusercontent.com/82976159/276598651-548bd84c-d31f-4b78-afe2-c92a1efb296a.png)
> 
> There should be like an alert sayiing you have to be logged in first (if you want users to logged in before using the app). I feel this should be a quick tool to use, no need for logging in, just paste your link and grab.. but anyways, i also don't know how stuffs are on the backend

You're absolutely right, While I understand the convenience of quickly generating links without logging in, but Authentication is necessary to maintain the security and integrity of the service and prevent misuse and spam requests on our server

**Comment by DhananjayThomble** [comment]
Certainly, we can implement an alert to inform users that they need to be logged in
