### ISSUE TITLE
Create User Profile Page - Backend

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#112]
Develop the backend logic to support the user profile page on the frontend, allowing users to view and edit their profile information.

**Tasks:**
- Create API endpoints for retrieving and updating user profile information.
- Implement the necessary database operations to retrieve and update user data.
- Ensure proper validation and error handling on the backend.

**Comment by Honey2339** [comment]
Interesting , I would like to contribute

**Comment by Honey2339** [comment]
Im setting up the application and i came across Email Provider , Can u help me how to setup the Email Provider part?

**Comment by samuelogboye** [comment]
@Honey2339 if you need help, ill love to join you

**Comment by Honey2339** [comment]
@samuelogboye Yeah sure! , i need Email related environment variables so that i can test the development server

**Comment by DhananjayThomble** [comment]
> @samuelogboye Yeah sure! , i need Email related environment variables so that i can test the development server

You can refer this : https://youtube.com/shorts/_INB5cm29LQ?si=Na-rImQSXKfxP2HR

Alternatively, you can even use your own Gmail account. Just search for "how to use Nodemailer with Gmail"

**Comment by Honey2339** [comment]
Please review the above mentioned PR

**Comment by DhananjayThomble** [comment]
> Please review the above mentioned PR

Thanks @Honey2339, I've merged the PR. I'd like to ask if you could add validators for this API. You can use the signup API as a reference.
