### ISSUE TITLE
Design UI for Public User Profile Page( issue #127 )

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#138]

**Comment by darklionHu** [comment]
Hey! Can you assign this to me?
Also, just to make this task more clear:
- The page should include the user's name, profile picture, and bio/description. (extra suggestion: maybe a number that shows how many shortlinks did the user share, or how many views did all of the shortlinks get overall?)
- Below the basic informations there should be a list of the short URLs that the user has made.
Did I forget anything?

**Comment by DhananjayThomble** [comment]
> Hey! Can you assign this to me? Also, just to make this task more clear:
> 
> * The page should include the user's name, profile picture, and bio/description. (extra suggestion: maybe a number that shows how many shortlinks did the user share, or how many views did all of the shortlinks get overall?)
> * Below the basic informations there should be a list of the short URLs that the user has made.
> 
> Did I forget anything?

You captured everything, @darklionHu, and your suggestion is also great. If you have more ideas, feel free to try them. We look forward to your creativity.

**Comment by darklionHu** [comment]
@DhananjayThomble where should I upload the design? I can export them in most image and document file extensions.
I'll most likely finish this assignment tomorrow and then improve on it based on feedbacks and suggestions if needed.

**Comment by DhananjayThomble** [comment]
> @DhananjayThomble where should I upload the design? I can export them in most image and document file extensions. I'll most likely finish this assignment tomorrow and then improve on it based on feedbacks and suggestions if needed.

You can create a 'design' directory in the root of the project and upload necessary doc and img files there.

**Comment by DhananjayThomble** [comment]
Hello @darklionHu, I really liked the design and already merged it. Now, we need your help with designing another page where users can view the lists of other registered SnapURL users. They should be able to click on the lists to access the URLs and bio/description, which you've already designed.

**Comment by darklionHu** [comment]
> Hello @darklionHu, I really liked the design and already merged it. Now, we need your help with designing another page where users can view the lists of other registered SnapURL users. They should be able to click on the lists to access the URLs and bio/description, which you've already designed. 

Hey, I'm really glad you liked it! 
I'll start working on it and will finish the new design this saturday.
