### ISSUE TITLE
Make API Endpoints Consistent in Backend & Frontend

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#14]
**Issue Description:**
To enhance the maintainability and consistency of our URL Shortener App, we need to ensure that API endpoints are consistent across both the backend and frontend codebases. Currently, they might be hard-coded in places, which can lead to issues when transitioning between development, testing, and production environments.

1) Create .env files in both the backend and frontend codebases.

2) Define the necessary environment variables in these .env files.

3) Update the frontend and backend code to use these environment variables for API endpoint configuration.

**Comment by saimaheshtaduri** [comment]
I'm interested to explore this issue. @DhananjayThomble

**Comment by NikhilBabhulkar** [comment]
I'm interested to do this task
