### ISSUE TITLE
Convert All Bootstrap Components to Material-UI

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#147]
The following components must be converted from Bootstrap to Material-UI and the Bootstrap CDN should be removed to maintain consistency and utilize Material-UI features. Also test for mobile responsiveness:
1) Signup
2) Login

ref: https://mui.com/material-ui/

**Comment by keshav-nischal** [comment]
I am interested to work this issue. Please assign this to me.

**Comment by chiragmalik2612** [comment]
I want to work on this issue, please assign
