### ISSUE TITLE
Enhancement: Implement Validation in Authentication Controllers

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#15]
we should implement validation for input data in the authentication controllers. This includes input validation for user registration and login. Additionally, we should consider separating these controllers into their own dedicated files for better code organization.

**Tasks:**

* Create separate controller files for user registration and login.
* Implement input validation for user registration and login.
* Ensure validation checks for required fields and data format.
* Update routes to use the newly created controller files.

**Note:** You may want to use a validation library like express-validator

**Comment by corneliusdevs** [comment]
I'm interested in resolving this.
I can extract the logic into their own separate files

However, I have a few questions.

what am I validating for? 
You seem to have validated that the name, email and password are not empty. Are there extra validation checks that you want to be implemented?

**Comment by GawaliAbhishek** [comment]
I am Interested to fix this issue. I have used this kind of validations in my projects.  I can fix it in very proper way
