### ISSUE TITLE
Misalignment of icons and their name in the Navigation bar

### ISSUE THREAD

**Issue by sagar-io** [DhananjayThomble/URL-Shortener-App#154]
In the navigation bar, the icons and their name is not aligned centered properly example see the home and home's icon

![image](https://github.com/DhananjayThomble/URL-Shortener-App/assets/86215447/8252ce38-7c60-4a15-8bbb-44974ef834cd)

**Comment by GOKULNATH-RS** [comment]
I would love to work on this issue. Will you assign me?
