### ISSUE TITLE
Design User Profile and Settings UI/UX

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#158]
**User Profile:**

- Users can choose whether their profiles should be public or private.
- Display the user's profile picture prominently.
- Show the user's name, bio and any additional relevant information. (including edit functionality)
- Users can add links to their social media profiles (e.g., Twitter, LinkedIn).
- Users can see their favourite links.
- Design an area for users to update their profile picture.
- Ensure responsive design for desktop and mobile users.

**Deliverables:**

- High-fidelity UI/UX designs
- Design files in Figma or Adobe XD.
- Resources and assets required to implement these profile and settings features.

**Comment by GOKULNATH-RS** [comment]
I would love to work with this issue. Can I work?

**Comment by DhananjayThomble** [comment]
> I would love to work with this issue. Can I work?

Great! I'm looking forward to your contributions @GOKULNATH-RS
