### ISSUE TITLE
Enhancement: Implement Validation in URL Controllers

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#16]
Write input validation for creating and updating shortened URLs, ensuring that URLs are valid and adhere to specific criteria. Additionally, we should consider separating these controllers into their own dedicated files for better code organization.

**Tasks:**

* Create separate controller files for creating, updating, and managing shortened URLs.
* Implement input validation for URL creation and updates.
* Ensure validation checks for valid URLs and other relevant criteria.
* Update routes to use the newly created controller files.

**Note:** You may want to use a validation library like express-validator

**Comment by GawaliAbhishek** [comment]
I have understand this issue and want to fix this issue. I have worked upon such things in my projects.
