### ISSUE TITLE
Feature: Implement Forgot Password API

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#17]
As part of enhancing user account management in the URL-Shortener-App, we need to implement a "Forgot Password" feature. This feature will allow users who have forgotten their passwords to reset them securely. To achieve this, we should create a new API endpoint that handles password reset requests.

**Tasks:**

* Create a new API endpoint, e.g., /api/auth/forgot-password, for handling password reset requests.
* Implement logic to generate a unique reset token for the user and send it to their registered email address.
* Implement the logic to reset the user's password securely based on the token.
* Include appropriate error handling and validation to ensure the security of the reset process.

**Comment by NikhilBabhulkar** [comment]
I am interested in solving this issue
