### ISSUE TITLE
Feature: Implement Email Verification API

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#18]
To enhance the security and authenticity of user accounts in the URL-Shortener-App, we should implement an "Email Verification" feature. This feature ensures that users provide valid email addresses and allows us to verify their accounts before they can fully access the system.

**Tasks:**

* Create a temporary link in the email that the user can click to verify their email address.
* Update the user's account status to "verified" once the email is successfully verified.
* Include appropriate error handling and validation to ensure the security of the email verification process.

**Comment by NikhilBabhulkar** [comment]
I am interested in Adding this feature.I will add Api and create the required changes in frontend as well
