### ISSUE TITLE
Feature: Send Welcome Email to Users After Signup

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#20]
To enhance the user experience and provide a warm welcome to new users, we should implement a feature that sends a welcome email to users immediately after they sign up. This welcome email can contain a friendly message, important information about the service, and possibly some useful tips on getting started.

**Tasks:**

* Implement an email sending functionality within the authentication controller.
* Create a welcome email template that includes a personalized message and any necessary instructions.
* Trigger the sending of the welcome email when a user successfully signs up.
* Ensure that the email sending process is robust and handles any potential errors or exceptions gracefully.

**Comment by NikhilBabhulkar** [comment]
I am interested to resolve this issue
