### ISSUE TITLE
Refactor Authentication Controller with Improved Comments

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#21]
The authentication controller code needs to be refactored for better readability and maintainability. This includes adding clear and comprehensive comments to explain each section of the code.

**Tasks:**

* Review the existing authentication controller code.
* Add comments to describe the purpose of the controller and its functions.
* Include comments within each function to explain their roles and logic.
* Ensure that variable names and code structure are self-explanatory.
* Refactor any complex or unclear code segments to improve readability.

**Comment by corneliusdevs** [comment]
I can fix this issue.
Also, for security sake, passwords shouldn't be stored directly in your database.

They should be encrypted first. 

I can also add this functionality if you assign me to this issue.
