### ISSUE TITLE
Refactor URL Controller with Improved Comments

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#22]
The URL controller code needs to be refactored to enhance code quality and readability. This includes adding comprehensive comments to clarify the purpose of the controller and its functions.

**Tasks:**

* Review the existing URL controller code.
* Add comments to explain the controller's role and objectives.
* Include comments within each function to describe their functionalities and logic.
* Ensure that variable names and code structure are self-descriptive.
* Refactor any complex or unclear code segments to improve overall readability.

**Comment by MayurShastrakar** [comment]
I am interested to solve this issue
