### ISSUE TITLE
Document Authentication API Endpoints with Swagger

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#23]
**Tasks:**

* Define Swagger annotations and comments for all Authentication API endpoints.
* Ensure that the Swagger documentation includes information about request parameters, response formats, and any required authentication.
* Validate that the Swagger UI is accessible and functional, allowing developers to interact with the API directly through the documentation.

**Comment by NikhilBabhulkar** [comment]
I am Interested in solving this issue.

**Comment by Abhijeet-Tathod** [comment]
Sir , I am Interested in solving this issue.
