### ISSUE TITLE
Document URL API Endpoints with Swagger

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#24]
**Tasks:**

* Define Swagger annotations and comments for all URL API endpoints.
* Ensure that the Swagger documentation includes information about request parameters, response formats, and any required authentication.
* Validate that the Swagger UI is accessible and functional, allowing developers to interact with the API directly through the documentation.

**Comment by Abhijeet-Tathod** [comment]
Sir ,I have previous experience working on Swagger UI and I would like to work on this particular issue. I would like to work on this!!
