### ISSUE TITLE
Design Landing Page

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#28]
The current landing page of our application lacks an appealing design and user-friendly layout. To create a strong first impression and engage users effectively, we need to revamp the landing page.

**Tasks:**

* Create a new MUI-based landing page component.
* Use MUI components like  Typography, Button, Grid, and Paper to structure the page.
* Design a clean and visually appealing layout with relevant images and content.
* Ensure that the landing page is responsive and mobile-friendly.
* Implement smooth transitions and animations for a polished user experience.
* Test the landing page on different devices and screen sizes to ensure it looks good and functions well.

**Comment by vanshika8750** [comment]
i can improve ui. please assign it to me

**Comment by CoderRedwing** [comment]
kindly assign this me

**Comment by GauriZamare** [comment]
Sir i am interested to work work on this.

**Comment by DhananjayThomble** [comment]
#79
