### ISSUE TITLE
Design Navbar Using Material-UI Components

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#29]
We should design a navigation bar using Material-UI (MUI) components to ensure consistency and responsiveness. MUI offers a collection of ready-to-use components that will help us create an elegant and user-friendly navbar.

**Tasks:**

* Create a new navbar component using Material-UI components.
* Utilize MUI's AppBar, Toolbar, Typography, and IconButton components to structure the navbar.
* Design the navbar layout, including the logo or app name, navigation links, and user account options.
* Implement responsive behavior, ensuring that the navbar adapts to different screen sizes.

**Comment by MasterIfeanyi** [comment]
@DhananjayThomble please assign this to me.

**Comment by CoderRedwing** [comment]
kindaly assign this to me.

**Comment by YadnikaDabhade** [comment]
Sir , I am interested to work on navbar . Please assign this task to me
