### ISSUE TITLE
Design Footer Using Material-UI Components

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#30]
We should design a footer using Material-UI (MUI) components to ensure consistency and responsiveness. MUI offers a collection of ready-to-use components that will help us create an elegant and user-friendly footer.

**Tasks:**

* Create a new footer component using Material-UI components.
* Utilize MUI's Typography, Link, and Grid components to structure the footer.
* Design the footer layout, including sections for important links, contact information, and copyright details.
* Implement responsive behavior, ensuring that the footer adapts to different screen sizes.

**Comment by MasterIfeanyi** [comment]
@DhananjayThomble Please assign this to me.

**Comment by YadnikaDabhade** [comment]
Sir I am interested to create a new footer component . Please assign this task to me

**Comment by Shivam36998** [comment]
@YadnikaDabhade are you still working on it ?

**Comment by DhananjayThomble** [comment]
#
