### ISSUE TITLE
Integrate Chrome Extension with Backend API

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#32]
To enable our Chrome extension to interact with our backend server, we need to implement the necessary API integration. This will allow the extension to send requests to the server, retrieve data, and perform actions like URL shortening.

**Tasks:**

* Create API endpoints on the backend to handle requests from the Chrome extension. These endpoints should include functionality for URL shortening and any other relevant features.
* Update the Chrome extension code to send HTTP requests to the backend API endpoints.
* Implement error handling to gracefully handle cases where the backend API is unavailable or returns errors.
* Ensure that the extension securely communicates with the backend using appropriate authentication mechanisms.
* Test the integration thoroughly to confirm that the extension can successfully interact with the backend and perform actions like URL shortening.

**Comment by Abhijeet-Tathod** [comment]
Sir , I would like to work on this!!
