### ISSUE TITLE
Design Share Page

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#40]
We need to create an appealing and user-friendly Share Page for our application.

**Tasks:**

* Design Share Page UI 
* Shortened URL Display: Display the shortened URL prominently on the Share Page, making it easy for users to copy and share.

* Social Sharing Icons: Include social sharing icons (e.g., Twitter, Facebook, LinkedIn) that users can click to share the shortened URL directly on their social media profiles.

* Copy to Clipboard Button: Add a "Copy to Clipboard" button next to the shortened URL to allow users to quickly copy the URL with a single click.

* Responsive Design: Ensure that the Share Page is responsive and works seamlessly on various devices and screen sizes.

* Consistent Styling: Maintain a consistent design style with the rest of the application, including typography, color schemes, and button styles.

**Comment by YadnikaDabhade** [comment]
Sir, I'm Interested in working on this issue , Please assign it to me
