### ISSUE TITLE
Implement Password Reset Page

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#41]
We need to create a Password Reset Page to allow users who have forgotten their passwords to reset them securely. This page should be user-friendly and seamlessly integrate with the /auth/forgot-password and /auth/reset-password APIs.

**Tasks:**

* Design Password Reset Page UI: Design a user-friendly Password Reset Page UI that guides users through the password reset process. This page should include clear instructions and input fields for email and the new password.

* Password Reset Request Form: Create a form on the Password Reset Page where users can enter their registered email address to request a password reset.

* API Integration (Forgot Password): Integrate the /auth/forget-password API to handle the password reset request. When users submit their email address, this API will send them a reset link or token via email.

* Email Confirmation: After users submit their email for a password reset, display a confirmation message instructing them to check their email for further instructions.

* Reset Password Form: Once users receive the password reset email and click the reset link, they should be redirected to a page where they can enter a new password.

* API Integration (Reset Password): Integrate the /auth/reset-password API to securely reset the user's password.

* Error Handling: Implement error handling for cases where the email address is not found, or the reset token/link is invalid or expired. Provide clear error messages.

* Confirmation Message: Display a confirmation message to users once their password has been successfully reset.

**Comment by YadnikaDabhade** [comment]
Sir , I am interested to design Password reset page UI , Please assign this task to me.
