### ISSUE TITLE
Domain Verification for Custom Domains

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#45]
**Description:** This issue involves implementing domain verification methods to ensure that users own the custom domains they intend to use. Domain verification is crucial for security and authorization purposes.
- **Tasks:**
  - Define and implement domain verification mechanisms (e.g., DNS TXT records, HTML file upload, meta tags).
  - Document the domain verification process.
  - Ensure that only verified domains can be used for custom short URLs.
- **Acceptance Criteria:** Users should be able to verify ownership of their custom domains, and the system should restrict the use of unverified domains.
- **Additional Information:** Detailed instructions on domain verification can be found in our [Custom Domain Feature Implementation Guide](https://github.com/DhananjayThomble/URL-Shortener-App/wiki/Custom-Domain-Feature-Implementation-Guide).

**Comment by ArunBohra12** [comment]
I'd like to take this one
