### ISSUE TITLE
Implement Backend Logic for Custom Back-Halves

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#50]
**Description:**
This sub-issue focuses on implementing the server-side logic required to handle custom back-halves when generating shortened URLs.

**Tasks:**
1. Modify the database schema to include a field for custom back-halves in the URL records.
2. Ensure that custom back-halves are unique per user to prevent conflicts.
3. Create server-side logic to generate shortened URLs with custom back-halves.
4. Implement checks to verify the uniqueness and validity of custom back-halves.
5. Update the API endpoints and controllers to accommodate custom back-halves.

**Comment by Sundroid-ops** [comment]
Hey @DhananjayThomble I want to work on this.

**Comment by Sundroid-ops** [comment]
@DhananjayThomble can you give me a example of how should a custom back-half url should look like for this project.

**Comment by DhananjayThomble** [comment]
Sure, check the wiki section, I have written detailed description there.

**Comment by DhananjayThomble** [comment]
> Sure, check the wiki section, I have written detailed description there.

https://github.com/DhananjayThomble/URL-Shortener-App/wiki/Custom-URL-(Back%E2%80%90Halves)-Feature

**Comment by Sundroid-ops** [comment]
Hey @DhananjayThomble so basically I have some doubts :

1. Should I like create a custom link once a short link has been created and stored in DB or create both custom and short url simultaneously where users pass a url-link and a custom input.
2. Create a diff route for custom or work with the existing short url route.

**Comment by DhananjayThomble** [comment]
> Hey @DhananjayThomble so basically I have a doubt should I Create a diff route for custom Url's or work with the existing short url route.

To keep the system straightforward, I think it's a good idea to work with the existing short URL route and enhance it to support custom back-halves. This approach maintains consistency and ensures that users can generate both traditional short URLs and custom back-halves from the same route.

You can include a feature flag or a parameter in the request to distinguish between regular and custom back-halve URLs when generating them. This way, users can choose whether to customize the back-halve or let the system generate a random one for them.
