### ISSUE TITLE
Implement Support for Custom Back-Halves

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#51]
**Description:**
This sub-issue focuses on updating the frontend user interface to allow users to enter custom back-halves when shortening URLs.

**Tasks:**
1. Update the frontend user interface to include an input field for custom back-halves.
2. Implement client-side validation to ensure custom back-halves meet specified criteria (e.g., length, allowed characters).
3. Integrate the frontend with the backend to support custom back-halves.

**Comment by theprinceraj** [comment]
@DhananjayThomble 
Do we have to code the backend for this issue as well? Or are we supposed to code the front end only?

**Comment by DhananjayThomble** [comment]
> Hi @DhananjayThomble Do we have to code the backend for this issue as well? Or are we supposed to code the front end only?

Backend API is already there for this feature, now we just need to develop the frontend part.

**Comment by theprinceraj** [comment]
Hi, I have a question regarding the .env variables of backend folder. How to find the following:
EMAIL_HOST=<your-email-host>, e.g. smtp.gmail.com
EMAIL_PORT=<your-email-port>, e.g. 587
EMAIL_HOST_USER=<your-email-host-user>, e.g. john@gmail.com
EMAIL_HOST_PASSWORD=<your-email-host-password>, e.g. john123
JWT_SECRET=<your-jwt-secret>
SESSION_SECRET=<your-session-secret>

**Comment by theprinceraj** [comment]
@DhananjayThomble I hope that helps! 🥳

**Comment by DhananjayThomble** [comment]
Currently, we are using a browser prompt to edit the custom back-half of the URL. However, it would be better if we use a separate model that can provide real-time availability of the back-half( The part of your short link after the last forward slash ) and suggest alternatives if it's not available. By doing this, we can significantly improve the user experience. 

For instance, we could develop a model like https://mui.com/material-ui/react-modal 
If anyone is interested in working on this issue, please let me know.

**Comment by SamirMishra27** [comment]
Hi @DhananjayThomble!
I've forked this project and successfully set it up. I've studied the code a bit, and I'm super confident in implementing this feature of custom back halves, including a modal form for the front-end. (Before oct 31st)
Please assign me this issue.

I also would like to get in touch with you on Discord so that I can ask any doubt that arise while working with this project.
My Discord username is [@samir5](https://discord.com/users/278094147901194242).

**Comment by DhananjayThomble** [comment]
> Hi @DhananjayThomble! I've forked this project and successfully set it up. I've studied the code a bit, and I'm super confident in implementing this feature of custom back halves, including a modal form for the front-end. (Before oct 31st) Please assign me this issue.
> 
> I also would like to get in touch with you on Discord so that I can ask any doubt that arise while working with this project. I've sent you a DM there, please check! My Discord username is [@samir5](https://discord.com/users/278094147901194242).

Sure, @SamirMishra27 👍
