### ISSUE TITLE
Update Database Schema for Custom Back-Halves

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#52]
**Description:**
This sub-issue deals specifically with modifying the database schema to accommodate custom back-halves in URL records.

**Tasks:**
1. Modify the database schema to include a field for custom back-halves in the URL records.
2. Ensure that custom back-halves are unique per user to prevent conflicts.

**Comment by Sundroid-ops** [comment]
@DhananjayThomble Let me work on this.
