### ISSUE TITLE
Test Custom Back-Halves Feature

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#53]
**Description:**
This sub-issue is dedicated to thoroughly testing the custom back-halves feature to ensure it functions correctly and doesn't conflict with existing short URLs.

**Tasks:**
1. Test the feature to verify that custom back-halves work as expected.
2. Verify that custom back-halves do not conflict with existing short URLs.

**Comment by corneliusdevs** [comment]
Please assign me to this.
