### ISSUE TITLE
Update Documentation for Custom Back-Halves Feature

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#54]
**Description:**
This sub-issue involves updating the API documentation and user guides to explain how users can use the custom back-halves feature effectively.

**Tasks:**
1. Update the API documentation to include details on using custom back-halves.
2. Provide examples and best practices for creating custom back-halves.

**Comment by zainbinfurqan** [comment]
@DhananjayThomble  can i work on this issue?

**Comment by AnikethDeb2004** [comment]
@DhananjayThomble assign me

**Comment by SamirMishra27** [comment]
I assume this issue has been stale.

Once #175 is merged, please assign this to me and I'll update the swagger documentation for `/api/url` and `/api/url/custom` routes for custom back links as implemented. (<https://github.com/DhananjayThomble/URL-Shortener-App/pull/175>)
