### ISSUE TITLE
Design User Feedback Form Interface (Frontend)

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#57]
**Description:**
Design an intuitive and visually appealing user feedback form interface within the application's frontend. This interface will allow users to provide feedback, report issues, or suggest improvements.

**Tasks:**
1. Create a user-friendly feedback form layout.
2. Include fields for users to enter feedback, report issues, or offer suggestions.
3. Ensure responsiveness for various device sizes.
4. Design a clear submission button for users to submit their feedback.
5. Implement validation for the frontend to ensure users provide essential information and valid feedback.
6. Design any additional features such as attaching screenshots or files

**Comment by Shivam36998** [comment]
@DhananjayThomble can you please assign me this issue
and clarify a bit more where you want that button/icon to be ?

**Comment by DhananjayThomble** [comment]
> @DhananjayThomble can you please assign me this issue and clarify a bit more where you want that button/icon to be ?

You can place a link to the feedback form in the footer section

**Comment by Shivam36998** [comment]
@DhananjayThomble i have made it but your footer do not have working links feature, should i try to change it in working forms

**Comment by DhananjayThomble** [comment]
> @DhananjayThomble i have made it but your footer do not have working links feature, should i try to change it in working forms

sure

**Comment by Nupoor10** [comment]
Hello, can I work on this?
