### ISSUE TITLE
Update Frontend Links (Frontend)

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#60]
Update links in the frontend application to use the new URL routing format when generating and displaying shortened links.

**Comment by Judge-Paul** [comment]
Hey, @DhananjayThomble can I work on this?

**Comment by DhananjayThomble** [comment]
Sure @Judge-Paul  👍

**Comment by Shashankpantiitbhilai** [comment]
Can u please assign this to me
