### ISSUE TITLE
Design Signup Page

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#76]
**Tasks:**

* Layout Design: Create a clean and visually appealing layout for the signup page. Consider the placement of form fields, buttons, and any additional elements.

* Form Design: Design the signup form with fields for users to enter their email, password, name, and any other required information.

* Validation: Implement client-side validation to provide real-time feedback on user input, helping to prevent errors and improve the user experience.

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue can you assign me this?

**Comment by Shashankpantiitbhilai** [comment]
I am interested please assign this to me
