### ISSUE TITLE
Design GitHub Contributors Page (Frontend)

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#78]
This issue addresses the frontend design of our GitHub Contributors page for the URL Shortener App. The goal is to create an appealing layout that showcases contributors' names, GitHub profile pictures, and links to their GitHub profiles

**Comment by AKASH-PRASAD7** [comment]
Hey, I would like to work on this issue can you assign me this?

**Comment by Shashankpantiitbhilai** [comment]
i would like to work on this,please assign this to me

**Comment by parthrc** [comment]
@DhananjayThomble hey, I have created a pull request for this issue please check

**Comment by joelcr10** [comment]
hey @DhananjayThomble , I would like to design and develop the contributors page , kindly assign me this issue
