### ISSUE TITLE
Implement QR Code Generation for Shortened URLs

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#85]
Implement the functionality to generate QR codes for shortened URLs. This enhancement will enable users to easily share links via printed materials or mobile devices by scanning the QR code.

**Tasks:**

* Integrate a QR code generation library or service into the application.
* Develop an API endpoint or service to generate QR codes for shortened URLs.

**Comment by Kiran-Alex** [comment]
I would like to work on this issue please assign this issue to me

**Comment by Kiran-Alex** [comment]
hey dhananjay can you tell me what branch are you actively using ? because when i ran the main branch i'm getting the frontend which is not same as the deployed one 
![image](https://github.com/DhananjayThomble/URL-Shortener-App/assets/98690069/ba3354db-aaf8-4e08-89cb-c4e53fa9b3cf)

**Comment by DhananjayThomble** [comment]
> hey dhananjay can you tell me what branch are you actively using ? because when i ran the main branch i'm getting the frontend which is not same as the deployed one ![image](https://user-images.githubusercontent.com/98690069/275324018-ba3354db-aaf8-4e08-89cb-c4e53fa9b3cf.png)

Hello @Kiran-Alex, you're using the correct branch. You can proceed with it as the deployed branch uses an old design. Eventually, we will transition to this new design.

**Comment by joelcr10** [comment]
I would like to work on this issue, so please assign me this issue.

**Comment by ddddami** [comment]
Hii there, would like to work on this issue too..

**Comment by joelcr10** [comment]
hey @DhananjayThomble, whenever I run the app on my local machine and try to shorten a URL, it gives a POST 401 (unauthorized) error. Can you please help me fix this issue.
![error2](https://github.com/DhananjayThomble/URL-Shortener-App/assets/67091039/c4f49375-d80e-43ba-9a6e-db3d2bf86bf2)

**Comment by DhananjayThomble** [comment]
> hey @DhananjayThomble, whenever I run the app on my local machine and try to shorten a URL, it gives a POST 401 (unauthorized) error. Can you please help me fix this issue. ![error2](https://user-images.githubusercontent.com/67091039/276707366-c4f49375-d80e-43ba-9a6e-db3d2bf86bf2.png)

Hello @joelcr10 , pls make sure to log in before using the app. If you're still facing any issues then let me know.
