### ISSUE TITLE
Frontend Development for "Link-in-Bio" Page

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#90]
Implement the frontend components and functionality for the "Link-in-Bio" page using React. This page will allow users to showcase multiple links in one place, making it easier for them to share various resources or content with their audience.

**Tasks:**
* Create a new page in the frontend application that users can access to manage their "Link-in-Bio" pages.
* Design the layout and components for the "Link-in-Bio" page, taking reference from bit.ly's link-in-bio feature (https://bitly.com/pages/products/link-in-bio) for inspiration.

**Comment by Pree46** [comment]
Hey @DhananjayThomble can i work on this issue? or is there someone who is already working on this?

**Comment by DhananjayThomble** [comment]
> Hey @DhananjayThomble can i work on this issue? or is there someone who is already working on this?

Sure, you can work on this. There is no one else assigned to it at the moment

**Comment by KSSaiTeja** [comment]
if the issue still open i am interested to start work on this issue..

**Comment by DhananjayThomble** [comment]
> if the issue still open i am interested to start work on this issue..

Yes, It's open. however I believe @Pree46 is still working on it

**Comment by KSSaiTeja** [comment]
ok then i will start work on this and raise a PR

**Comment by Pree46** [comment]
Hey @DhananjayThomble I have created a pull request. Kindly go through it. Let me know if i need to edit anything. Thank you for letting me work on this,

**Comment by DhananjayThomble** [comment]
> Hey @DhananjayThomble I have created a pull request. Kindly go through it. Let me know if i need to edit anything. Thank you for letting me work on this,

Thanks, @Pree46 for the stellar PR 🎉
