### ISSUE TITLE
Database Schema and Models for "Link-in-Bio"

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#92]
Define the database schema and models required to store "Link-in-Bio" page data, including user settings and link information.

**Tasks:**
* The Schema may include the following fields:
  * User ID: The unique identifier of the user who owns the "Link-in-Bio" page.
  * Page Title: The title of the "Link-in-Bio" page, allowing users to customize how it appears.
  * Links: Store information about each link, including the title, URL, and optional description.
* Set up relationships between users and their "Link-in-Bio" pages.

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
Can you assign this to me. I can work on it.
