### ISSUE TITLE
Update 'redirectToOriginalUrl' Controller for Custom URL Feature

### ISSUE THREAD

**Issue by DhananjayThomble** [DhananjayThomble/URL-Shortener-App#93]
This issue is part of the 'Custom URL (Back-Halves) Feature' milestone

**Tasks:**

* Modify the 'redirectToOriginalUrl' controller to handle both short URLs and custom URLs.
* Ensure that users can be redirected to the original URL correctly via both types of URLs.

**Comment by Shashankpantiitbhilai** [comment]
I am interested please assign this to me
