### ISSUE TITLE
For Making the Navbar active when clicked

### ISSUE THREAD

**Issue by Nabwinsaud** [DhananjayThomble/URL-Shortener-App#98]
This feature is for making the navbar highlight for making user experience better
Task:
  When clicked on Home it will highlight home and similarly to tohers
here is the demo images
![image](https://github.com/DhananjayThomble/URL-Shortener-App/assets/77477530/d5cea17a-c214-4072-8472-3d186da565da)
this show the active link in the navbar

**Comment by shivaaeshala** [comment]
Hi sir,
I would like to contribute but I am new to this, would you help me get started

**Comment by Nabwinsaud** [comment]
i have added pull request can you go through it ?

**Comment by shivaaeshala** [comment]
How should i do it can you help me

**Comment by shivaaeshala** [comment]
Sir, I have forked and created a clone to my local system and opened the repository in VScode. But how do I see the changes that I've made to the website can you help me with this

**Comment by Nabwinsaud** [comment]
> Sir, I have forked and created a clone to my local system and opened the repository in VScode. But how do I see the changes that I've made to the website can you help me with this

You can run the website and see the changes in your browser
